### ISSUE TITLE
Proposal to fix the doc of "Installation"

### ISSUE THREAD

**Issue by motxx** [zksync-sdk/zksync-sdk-go#2]
I know there are some issues on master branch README.md and it will be fixed by PR #1, so I'll talk about develop branch.

In develop branch:

> Download binary library for your platform from https://github.com/zksync-sdk/zksync-crypto-c/releases,

I downloaded `libzks-crypto.dylib` since my OS is mac, but I got the following error and couldn't execute the binary of my project.

```
dyld: Library not loaded: /Users/runner/work/zksync-crypto-c/zksync-crypto-c/target/release/deps/libzks_crypto.dylib
```
Note: there is no such path like `/Users/runner/...` on my PC.

I built `libzks-crypto.dylib` from the zksync-crypto-c source code and copied files under the `.../target/release/*` to `./libs`, and I finally could execute the binary of my project.

Maybe, is it needed some fixes to the develop branch documentation?

**Comment by motxx** [comment]
Sorry, I missed the following in README.md. I should have not install libzkscrypto.dylib.
> Requirements
> libzkscrypto.a

**Comment by VickMellon** [comment]
Yes, for macOS you need to download https://github.com/zksync-sdk/zksync-crypto-c/releases/download/v0.1.0/zks-crypto-macos-x64.a, rename it to `libzks-crypto.a` and put it to `./libs` directory of your project.
(by the way, you can use any other location, just specify right path in `CGO_LDFLAGS="-L./libs"`)

**Comment by motxx** [comment]
Thank you, I totally understand.

**Comment by adamxyzxyz** [comment]
hey stumbled upon this...do you have similar instructions for the python sdk?
